// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SplitBill.Data;

#nullable disable

namespace split_bill.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("SplitBill.Data.Entities.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CollectorParticipantId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatorToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServiceChargeType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ServiceChargeValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("TaxType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TaxValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("SplitBill.Data.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BillId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FrontedById")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FrontedByParticipantId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("ServiceChargeType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ServiceChargeValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("TaxType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TaxValue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("FrontedById");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("SplitBill.Data.Entities.ItemAssignee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InputType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("NominalAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ShareRatio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("ItemAssignees");
                });

            modelBuilder.Entity("SplitBill.Data.Entities.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BillId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BillId1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("BillId1")
                        .IsUnique();

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("SplitBill.Data.Entities.Payer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("TEXT");

                    b.Property<int>("BillId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("Payers");
                });

            modelBuilder.Entity("SplitBill.Data.Entities.Item", b =>
                {
                    b.HasOne("SplitBill.Data.Entities.Bill", "Bill")
                        .WithMany("Items")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SplitBill.Data.Entities.Participant", "FrontedBy")
                        .WithMany()
                        .HasForeignKey("FrontedById");

                    b.Navigation("Bill");

                    b.Navigation("FrontedBy");
                });

            modelBuilder.Entity("SplitBill.Data.Entities.ItemAssignee", b =>
                {
                    b.HasOne("SplitBill.Data.Entities.Item", "Item")
                        .WithMany("Assignees")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SplitBill.Data.Entities.Participant", "Participant")
                        .WithMany("AssignedItems")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("SplitBill.Data.Entities.Participant", b =>
                {
                    b.HasOne("SplitBill.Data.Entities.Bill", "Bill")
                        .WithMany("Participants")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SplitBill.Data.Entities.Bill", null)
                        .WithOne("Collector")
                        .HasForeignKey("SplitBill.Data.Entities.Participant", "BillId1");

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("SplitBill.Data.Entities.Payer", b =>
                {
                    b.HasOne("SplitBill.Data.Entities.Bill", null)
                        .WithMany("Payers")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SplitBill.Data.Entities.Participant", "Participant")
                        .WithMany("Payments")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("SplitBill.Data.Entities.Bill", b =>
                {
                    b.Navigation("Collector");

                    b.Navigation("Items");

                    b.Navigation("Participants");

                    b.Navigation("Payers");
                });

            modelBuilder.Entity("SplitBill.Data.Entities.Item", b =>
                {
                    b.Navigation("Assignees");
                });

            modelBuilder.Entity("SplitBill.Data.Entities.Participant", b =>
                {
                    b.Navigation("AssignedItems");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
